planner/apps/dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.dashboard, name="home"),
    path("set_active_board/", views.set_active_board, name="set_active_board"),
    path("set_active_category/", views.set_active_category, name="set_active_category"),
    path("board_manager/", views.board_manager),
    path("category_manager/", views.category_manager),
    path("reload_tasks/", views.reload_tasks),
]

planner/apps/task/urls.py
from django.urls import path

from . import views

app_name = "task"

urlpatterns = [
    path("new_task/", views.new_task, name="new_task"),
    path("task_manager/", views.task_manager, name="task_manager"),
    path("edit_task/", views.edit_task, name="edit_task"),
    path("delete_task/", views.delete_task),
    path(
        "set_task_extend_state/",
        views.set_task_extend_state,
        name="set_task_extend_state",
    ),
    path("subtask_manager/", views.subtask_manager),
    path("status_manager/", views.status_manager),
]

planner/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("planner.apps.dashboard.urls", namespace="dashboard")),
    path("account/", include("planner.apps.account.urls", namespace="account")),
    path("task/", include("planner.apps.task.urls", namespace="task")),
]

planner/apps/dashboard/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from planner.apps.account.models import UserAccount


class Board(models.Model):
    name = models.CharField(max_length=255)
    created_by = models.ForeignKey(
        UserAccount, related_name="board", on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "Board"
        verbose_name_plural = "Boards"

    def categories(self):
        qs = self.category.all()
        result = []
        for x in qs:
            result.append(x.name)
        return result

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=250)
    board = models.ForeignKey(Board, related_name="category", on_delete=models.CASCADE)
    created_by = models.ForeignKey(
        UserAccount, related_name="category", on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.name

planner/apps/task/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from planner.apps.account.models import UserAccount
from planner.apps.dashboard.models import Board, Category


class Task(models.Model):
    STATUS = (
        ("Planned", "Planned"),
        ("In Progress", "In Progress"),
        ("Testing", "Testing"),
        ("Completed", "Completed"),
    )
    board = models.ForeignKey(Board, related_name="task", on_delete=models.CASCADE)
    category = models.ForeignKey(
        Category, related_name="task", on_delete=models.CASCADE
    )
    status = models.CharField(max_length=50, choices=STATUS, default="Planned")
    name = models.CharField(max_length=250)
    created_by = models.ForeignKey(
        UserAccount, related_name="task", on_delete=models.CASCADE
    )
    description = models.TextField(max_length=500, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    extend_state = models.IntegerField(default=0)

    class Meta:
        verbose_name = _("Task")
        verbose_name_plural = _("Tasks")

    def __str__(self):
        return self.name


class Subtask(models.Model):
    name = models.CharField(max_length=250, blank=True)
    task = models.ForeignKey(Task, related_name="subtask", on_delete=models.CASCADE)
    is_complete = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("Subtask")
        verbose_name_plural = _("Subtasks")

    def __str__(self):
        return self.name

planner/apps/dashboard/forms.py
from django import forms
from django.forms import ModelForm

from .models import Board, Category


class BoardForm(ModelForm):
    class Meta:
        model = Board
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(BoardForm, self).__init__(*args, **kwargs)

        self.fields["name"].widget.attrs.update(
            {"class": "card", "placeholder": "Name"}
        )
        self.fields["name"].label = False
        self.fields["created_by"].widget = forms.HiddenInput()


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ["name"]

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)

        self.fields["name"].widget.attrs.update(
            {
                "class": "card",
            }
        )
        self.fields["name"].empty_label = None

planner/apps/dashboard/views.py
from django.http.response import JsonResponse
from django.shortcuts import render

from planner.apps.account.account import Account
from planner.apps.task.models import Category
from planner.apps.task.task import Task

from .dashboard import Dashboard, Sidebar
from .models import Board


def dashboard(request):
    dashboard = Dashboard(request)
    account = Account(request)

    if request.user.is_authenticated:
        is_guest = False
    else:
        is_guest = True

    user = account.getUser()
    boards = user.board.all()

    # if the session in not empty
    if not dashboard.session_check():

        # add all board to the session
        dashboard.add_all_boards(boards)

        # grab the first board from the Board model
        # and set the first board as active
        active_board = boards.first()

        # save the board's id as "active board" into the session
        dashboard.set_active_board_id(active_board.id)
        highlighted_board = active_board.id

        # set active category as ALL (-1)
        dashboard.set_active_category_id(active_board.id, -1)
        highlighted_category = -1

        # get the tasks
        tasks = active_board.task.all()

    # but if there is already something in the session
    else:
        # get the active board
        if not Board.objects.filter(pk=dashboard.get_active_board_id()).exists():
            active_board = boards.order_by("-id")[0]

        else:
            active_board = Board.objects.get(pk=dashboard.get_active_board_id())

        highlighted_board = active_board.id

        # get the active category
        active_category_id = int(dashboard.get_active_category_id(active_board.id))
        if active_category_id == -1:
            tasks = active_board.task.all()
            highlighted_category = -1
        else:
            category = Category.objects.get(pk=active_category_id)
            highlighted_category = category.id

            # get the tasks
            tasks = category.task.all()

    categories = active_board.category.all()

    statuses = ["Planned", "In Progress", "Testing", "Completed"]
    planned = tasks.filter(status="Planned")
    in_progress = tasks.filter(status="In Progress")
    testing = tasks.filter(status="Testing")
    completed = tasks.filter(status="Completed")

    task = Task()
    completed_subtasks = task.getCompletedSubtasks(tasks)
    task_ids = task.getTaskIds(tasks)

    context = {
        "total_tasks": user.task.all(),
        "tasks": tasks,
        "boards": boards,
        "categories": categories,
        "statuses": statuses,
        "planned": planned,
        "in_progress": in_progress,
        "testing": testing,
        "completed": completed,
        "highlighted_board": highlighted_board,
        "highlighted_category": highlighted_category,
        "task_ids": task_ids,
        "completed_subtasks": completed_subtasks,
        "is_guest": is_guest,
    }

    return render(request, "dashboard/dashboard.html", context)


def set_active_board(request):

    if request.POST.get("action") == "post":

        dashboard = Dashboard(request)
        board_id = request.POST.get("board_id")

        if board_id != dashboard.get_active_board_id():

            sidebar = Sidebar()
            dashboard.set_active_board_id(board_id)
            active_category_id = dashboard.get_active_category_id(board_id)

            active_board = Board.objects.get(pk=board_id)
            response = sidebar.categories_reload_json_response(active_board)
            response.update(
                {
                    "reload": True,
                    "active_category_id": active_category_id,
                }
            )

        else:
            response = {"reload": False}

        return JsonResponse(response)


def set_active_category(request):

    if request.POST.get("action") == "post":
        category_id = request.POST.get("category_id")

        dashboard = Dashboard(request)
        board_id = dashboard.get_active_board_id()

        if category_id != dashboard.get_active_category_id(board_id):
            dashboard.set_active_category_id(board_id, category_id)

            response = {"reload": True}
        else:

            response = {"reload": False}

        return JsonResponse(response)


def board_manager(request):
    dashboard = Dashboard(request)

    """
    ADD
    """
    if request.POST.get("action") == "add":
        name = request.POST.get("name")

        account = Account(request)
        user = account.getUser()

        board = Board.objects.create(name=name, created_by=user)

        dashboard.add_board(board.id)
        dashboard.set_active_board_id(board.id)

        sidebar = Sidebar()
        response = sidebar.boards_reload_json_response(request)
        response.update(
            {
                "message": 'Board "' + name + '" created',
                "active_board_id": board.id,
            }
        )

    """
    RENAME
    """
    if request.POST.get("action") == "rename":
        name = request.POST.get("name")
        board = Board.objects.get(pk=request.POST.get("id"))
        board.name = name
        board.save()

        response = {"message": "Board renamed", "name": name}

    """
    DELETE
    """
    if request.POST.get("action") == "delete":

        board_id = request.POST.get("id")

        board = Board.objects.get(pk=board_id)
        board.delete()

        user = request.user
        boards = user.board.all()

        # check if the active board is the same as the one we just deleted
        if dashboard.get_active_board_id() == board_id:
            # if so, then grab the last created board and set it as active
            active_board = boards.order_by("-id")[0]
            dashboard.set_active_board_id(active_board.id)
        else:
            active_board = boards.get(pk=dashboard.get_active_board_id())
            dashboard.set_active_board_id(active_board.id)

        active_category_id = dashboard.get_active_category_id(active_board.id)

        # remove deleted board from session
        dashboard.remove_board(board_id)

        sidebar = Sidebar()
        response = sidebar.boards_reload_json_response(request)
        response.update(sidebar.categories_reload_json_response(active_board))
        response.update(
            {
                "message": "Board deleted",
                "active_board_id": active_board.id,
                "active_category_id": active_category_id,
            }
        )

    return JsonResponse(response)


def category_manager(request):
    dashboard = Dashboard(request)

    """
    ADD
    """
    if request.POST.get("action") == "add":

        account = Account(request)
        user = account.getUser()

        name = request.POST.get("name")

        active_board = Board.objects.get(pk=dashboard.get_active_board_id())

        category = Category.objects.create(
            name=name, board=active_board, created_by=user
        )

        active_category_id = dashboard.get_active_category_id(active_board.id)

        response = {
            "message": 'Category "' + name + '" created',
            "added_category_id": category.id,
            "active_category_id": active_category_id,
        }

        sidebar = Sidebar()
        response.update(sidebar.categories_reload_json_response(active_board))

        if not request.user.is_authenticated:
            response.update(
                {"total_categories": user.category.all().count(), "is_guest": True}
            )
        else:
            response["is_guest"] = False

    """
    RENAME
    """
    if request.POST.get("action") == "rename":

        name = request.POST.get("name")
        pk = request.POST.get("id")

        category = Category.objects.get(pk=pk)
        category.name = name
        category.save()

        response = {"message": "Category renamed"}

    """
    DELETE
    """
    if request.POST.get("action") == "delete":

        account = Account(request)
        user = account.getUser()

        pk = request.POST.get("id")

        category = Category.objects.get(pk=pk)
        category.delete()

        active_board = Board.objects.get(pk=dashboard.get_active_board_id())
        dashboard.set_active_category_id(active_board.id, -1)

        sidebar = Sidebar()
        response = sidebar.categories_reload_json_response(active_board)

        if not request.user.is_authenticated:
            response.update(
                {"total_categories": user.category.all().count(), "is_guest": True}
            )
        else:
            response["is_guest"] = False

    return JsonResponse(response)


def reload_tasks(request):
    if request.method == "GET":

        dashboard = Dashboard(request)
        active_aboard_id = dashboard.get_active_board_id()
        active_category_id = int(dashboard.get_active_category_id(active_aboard_id))

        active_aboard = Board.objects.get(pk=active_aboard_id)

        task = Task()
        response = task.tasks_reload_json_response(active_category_id, active_aboard)

        return JsonResponse(response)

templates/dashboard/task/new_task.html
{% load static %}
<div class="row mt-4" id="new-task-wrapper">
  <div class="card card-body shadow form-bg">
    <div class="row">
      <div class="col mb-3">
        <div class="d-flex justify-content-between mb-3">
          <div class="text-white fs-4 newtask-boardName"></div>
          <div class="d-none delete-task-button">
            <button class="btn btn-block btn-sm fw500 w-100" data-placeholder="bottom" data-taskid="" data-taskname=""  id="delete-task">Delete</button>
          </div>
        </div>
        <div class="d-flex justify-content-between">
          <div class="">
            <label class="text-white mb-1">Category</label>
            <span class="d-flex">
              <select name="category" class="card bg-dark text-light newtask-categorySelect" id="id_category">
              </select>
              <a tabindex="0" role="button" data-sender="category" data-action="add" data-bs-placement="bottom"
                data-placeholder="Enter Category name" data-value="" data-source="new-task"
                class="rename-add-icon add-icon-task"><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22"
                  fill="orange" class="bi bi-plus-square" viewBox="0 0 16 16">
                  <path
                    d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                  <path
                    d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                </svg></a>
            </span>
          </div>
          <div class="task-status d-none">
            <label class="text-white mb-1">Status</label>
            <select name="status" class="card bg-dark text-light task-statusSelect" id="id_status">
            </select>
          </div>
        </div>
      </div>
    </div>

    <label class="text-white mb-1" for="id_name">Name</label>
    <input type="text" class="card bg-dark text-light" id="id_name" placeholder="Enter name" value="">
    <br>
    <label class="text-white mb-1" for="id_description">Description</label>
    <textarea class="card bg-dark text-light" name="description" id="id_description" cols="30" rows="5"
      placeholder="Enter description">{{ task.description }}</textarea>
    <br>


    <div id="subtask-div">
      <div class="row m-0">
        <label class="text-white mb-1 p-0" for="subtask-lb">Subtasks</label>
        <input type="text-sub" id="subtask-input" class="card subtask-lb bg-dark text-light col-10 p-0"
          placeholder="Enter subtask">
      </div>
      <br>

      <div id="individual-subtask"></div>

    </div>
    <br>

    <div class="task-bottom-section row align-items-end m-0">
      <div class="form-check form-switch mt-2 mb-2 custom-checkbox-wrapper">
        <input class="form-check-input custom-checkbox" id="create-and-continue" type="checkbox"
          id="flexSwitchCheckChecked">
        <label class="form-check-label text-white" for="flexSwitchCheckChecked">Create and continue</label>
      </div>
      <div class="row p-0">
        <div class="col-9">
          <button type="submit" data-edit="" data-taskID="" class="btn btn-success btn-block fw500 w-100"
            id="create-task"></button>
        </div>
        <div class="col-3 pe-0">
          <button class="btn btn-block fw500 w-100" id="cancel-task">Cancel</button>
        </div>
      </div>

    </div>

  </div>
</div>


<script>
  var CREATE_TASK_URL = '{% url "task:task_manager" %}';
  var DASHBOARD_HOME_URL = '{% url "dashboard:home" %}';
  var CSRF_TOKEN = '{{ csrf_token }}';
</script>
<script src="{% static 'task/js/new_task.js' %}" data-rel-js></script>

templates/dashboard/task/task.html
<div class="card text-white task shadow" id="panelsStayOpen-heading{{ task.id }}">
  <div class="card-header task-extend" data-index="{{ task.id }}" value="{{task.extend_state}}"
    data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse{{ task.id }}" aria-expanded="true"
    aria-controls="panelsStayOpen-collapse{{ task.id }}">

    <div class="card-subtitle fs-3 task-title-text">{{ task.name }}</div>

  </div>
  <div id="panelsStayOpen-collapse{{ task.id }}"
    class="accordion-collapse collapse {% if task.extend_state == 1 %}show{% endif %}"
    aria-labelledby="panelsStayOpen-heading{{ task.id }}">
    <div class="card-body">
      {% if task.description %}
      <div class="task-description-text fs-5 mb-2">Description:</div>
      <div class="card-text">{{ task.description}}</div>
      <hr>
      {% endif %}

      {% if task.subtask.all %}
      <div class="task-subtask-text fs-5 mb-2">Subtasks:</div>
      {% for subtask in task.subtask.all %}
      <span class="d-flex justify-content-between mb-3">
        <li class="card-subtitle card-subtask">{{ subtask.name }}</li>
        <div class="checkbox-div">
          <input type="checkbox" class="form-check-input custom-subtask-checkbox m-0" data-subtaskid="{{ subtask.id }}"
            {% if subtask.is_complete %}checked{% endif %}>
        </div>
      </span>
      {% endfor %}
      {% endif %}

    </div>
    <div class="card-footer">
      <h6 class="card-subtitle fw-light mt-1">Created by {{ task.created_by }} , on
        {{ task.date_created }}</h6>
      <hr>
      <div class="d-flex justify-content-between">
        <div class="">
          <button class="btn btn-block fw500 w-100" value="{{ task.id }}" id="edit-task">Edit</button>
        </div>
        <div class="">
          <div class="dropdown">
            <button data-display="static" class="btn dropdown-toggle task-status-button" type="button" id="dropdownMenuButton{{ task.id }}"
              data-bs-toggle="dropdown" aria-expanded="false">
              Move to
            </button>
            <ul class="dropdown-menu dropdown-menu-taskcard bg-dark" aria-labelledby="dropdownMenuButton{{ task.id }}">
              {% for status in statuses %}
                {% if task.status == status %}
                  <li class="taskcard-status current-status" data-status="{{ status }}" data-taskid="{{ task.id }}">{{ status }}</li>
                {% else %}
                  <li class="taskcard-status" data-status="" data-taskid="{{ task.id }}">{{ status }}</li>
                {% endif %}
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/dashboard/task/task_card.html
<div class="card text-white task shadow" id="panelsStayOpen-heading{{ task.id }}">
  <div class="card-header task-card-header-wrapper task-extend p-0" data-index="{{ task.id }}"
    value="{{task.extend_state}}" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse{{ task.id }}"
    aria-expanded="true" aria-controls="panelsStayOpen-collapse{{ task.id }}">
    <div class="d-flex justify-content-between task-card-header">
      <div class="card-subtitle fs-3 task-title-text">{{ task.name }}</div>
      {% if task.subtask.all %}
      <div class="subtask-circular-progress sub-progress-bar{{task.id}}" data-taskid="{{task.id}}" data-totalsubs="{{task.subtask.all|length}}" data-completed="" data-modulo="" data-toggle="">
        <div class="inner"></div>
        <div class="number"></div>
        <div class="circle">
          <div class="bar left">
            <div class="sub-progress"></div>
          </div>
          <div class="bar right">
            <div class="sub-progress"></div>
          </div>
        </div>
      </div>
      {% endif %}
    </div>

  </div>
  <div id="panelsStayOpen-collapse{{ task.id }}"
    class="accordion-collapse collapse {% if task.extend_state == 1 %}show{% endif %}"
    aria-labelledby="panelsStayOpen-heading{{ task.id }}">
    <div class="card-body">
      <div class="task-card-description">
        {% if task.description %}
        <div class="task-description-text fs-5 mb-2">Description:</div>
        <div class="card-text">{{ task.description}}</div>
        <hr>
      {% endif %}
      </div>
      <div class="task-card-subtasks">
        {% if task.subtask.all %}
        <div class="task-subtask-text fs-5 mb-2">Subtasks:</div>
        {% for subtask in task.subtask.all %}
        <span class="d-flex justify-content-between mb-3">
          <li class="card-subtitle card-subtask">{{ subtask.name }}</li>
          <div class="checkbox-div">
            <input type="checkbox" class="form-check-input custom-subtask-checkbox m-0" data-subtaskid="{{ subtask.id }}" data-taskid="{{task.id}}" 
              {% if subtask.is_complete %}checked{% endif %}>
          </div>
        </span>
        {% endfor %}
        {% endif %}
      </div>
    </div>
    <div class="card-footer">
      <h6 class="card-subtitle fw-light mt-1">Created by {{ task.created_by }} , on
        {{ task.date_created }}</h6>
      <hr>
      <div class="d-flex justify-content-between">
        <div class="">
          <button class="btn btn-block fw500 w-100" value="{{ task.id }}" id="edit-task">Edit</button>
        </div>
        <div class="">
          <div class="dropdown">
            <button data-display="static" class="btn dropdown-toggle task-status-button" type="button"
              id="dropdownMenuButton{{ task.id }}" data-bs-toggle="dropdown" aria-expanded="false">
              Move to
            </button>
            <ul class="dropdown-menu dropdown-menu-taskcard bg-dark" aria-labelledby="dropdownMenuButton{{ task.id }}">
              {% for status in statuses %}
              {% if task.status == status %}
              <li class="taskcard-status current-status" data-status="{{ status }}" data-taskid="{{ task.id }}">
                {{ status }}</li>
              {% else %}
              <li class="taskcard-status" data-status="" data-taskid="{{ task.id }}">{{ status }}</li>
              {% endif %}
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/dashboard/task/task_form.html
{% load static %}
<div class="row mt-4" id="new-task-wrapper">
  <div class="card card-body shadow form-bg">
    <div class="row">
      <div class="col mb-3">
        <div class="d-flex justify-content-between mb-3">
          <div class="text-white fs-4 newtask-boardName"></div>
          <div class="d-none delete-task-button">
            <button class="btn btn-block btn-sm fw500 w-100" data-placeholder="bottom" data-taskid="" data-taskname=""
              id="delete-task">Delete</button>
          </div>
        </div>
        <div class="d-flex justify-content-between">
          <div class="">
            <label class="text-white mb-1">Category*</label>
            <span class="d-flex">
              <select name="category" class="card bg-dark text-light newtask-categorySelect" id="id_category">
              </select>
              <div class="category-tooltip-div ms-2" data-bs-toggle="tooltip" data-bs-placement="right" title="">
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22"
                  fill="orange" class="bi bi-plus-square
                  {% if not user.is_authenticated and categories|length >= 3 %}
                  add-category-guest
                  {% else %}
                  rename-add-icon category-add-icon
                  {% endif%}
                  global-add-category-icon" viewBox="0 0 16 16" data-sender="category" data-action="add" data-bs-placement="right"
                data-placeholder="Enter Category name" data-value="" data-source="new-task">
                  <path
                    d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                  <path
                    d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                </svg>
                </div> 
            </span>
          </div>
          <div class="task-status d-none">
            <label class="text-white mb-1">Status</label>
            <select name="status" class="card bg-dark text-light task-statusSelect" id="id_status">
            </select>
          </div>
        </div>
      </div>
    </div>

    <label class="text-white mb-1" for="id_name">Name*</label>
    <input type="text" class="card  bg-dark text-light" id="id_name" placeholder="Enter name" value="">
    <br>
    <label class="text-white mb-1" for="id_description">Description</label>
    <textarea class="card bg-dark text-light" name="description" id="id_description" cols="30" rows="5"
      placeholder="Enter description">{{ task.description }}</textarea>
    <br>


    <div id="subtask-div">
      <div class="row m-0">
        <label class="text-white mb-1 p-0" for="subtask-lb">Subtasks</label>
        <input type="text-sub" id="subtask-input" class="card subtask-lb bg-dark text-light col-10 p-0"
          placeholder="Enter subtask...and press Enter">
      </div>
      <br>

      <div id="individual-subtask"></div>

    </div>
    <br>

    <div class="taskForm-bottom-section row align-items-end">
      <div class="form-check form-switch mt-2 mb-3 ms-3 custom-checkbox-wrapper">
        <input class="form-check-input custom-checkbox" id="create-and-continue" type="checkbox"
          id="flexSwitchCheckChecked">
        <label class="form-check-label text-white" for="flexSwitchCheckChecked">Create and continue</label>
      </div>
      <div class="col-9">
        <button type="submit" data-edit="" data-taskID="" class="btn btn-success btn-block fw500 w-100"
          id="create-task"></button>
      </div>
      <div class="col-3">
        <button class="btn btn-block fw500 w-100" id="cancel-task">Cancel</button>
      </div>

    </div>

  </div>
</div>


<script>
  var CREATE_TASK_URL = '{% url "task:task_manager" %}';
  var DASHBOARD_HOME_URL = '{% url "dashboard:home" %}';
  var CSRF_TOKEN = '{{ csrf_token }}';
</script>
<script src="{% static 'task/js/task_form.js' %}" data-rel-js></script>